# =======================
# server
# =======================
# tomcat port
server.port=8080

# JSP
spring.mvc.servlet.load-on-startup=1
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# =======================
# MyBati
# =======================
# Mapper XML
mybatis.mapper-locations=classpath:/mapper/**/*.xml

# Mapper
mybatis.type-aliases-package=devel

# =======================
# data-sources
# =======================
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://host/db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=username
spring.datasource.password=userpw

# =======================
# HikariCP
# =======================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# =======================
# session
# =======================
server.servlet.session.timeout=300m

# =======================
# logging
# =======================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

user.site.url=http://localhost:8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =======================
# file - develop
# =======================
file.upload.path=/Users/jongcheal./Desktop/file/
file.upload.url=/uploads/

# =======================
# file - real
# =======================
#file.upload.path=C:/upload/
#file.upload.url=C:/upload/

# =======================
# kakao - rest_api_key
# =======================
kakao.rest.api.key=kakaoApiKey
kakao.login.secret.key=kakaoSecretKey

# =======================
# naver - Client
# =======================
naver.client.id=naverClientId
naver.client.secret=naverClientSecret
